db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: "p@ssw0rd"
    POSTGRES_USER: "micropress"
    POSTGRES_DB: "micropress"

micropress:
  build: .
  links:
    - db
  environment:
    DATABASE_URL: "jdbc:postgresql://db:5432/micropress"
    USERNAME: "micropress"
    PASSWORD: "p@ssw0rd"

web-server:
  image: nginx:1.11
  links:
    - micropress
  volumes:
    - ./docker/default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
