drop table article_status_histories;
--;;
drop table articles;
--;;
drop table body_types;
--;;
drop table article_statuses;
--;;
drop table webhooks;
--;;
drop table events;
--;;
drop table user_histories;
--;;
drop table invitations;
--;;
drop table user_sessions;
--;;
drop table user_authorities;
--;;
drop table users;
--;;
drop table authorities;
--;;
drop table user_statuses;
--;;
