drop table article_tags;
--;;
drop table article_histories;
--;;
drop table articles;
--;;
drop table tags;
--;;
drop table body_types;
--;;
drop table article_statuses;
--;;
drop table webhooks;
--;;
drop table events;
--;;
drop table user_histories;
--;;
drop table invitee_authorities;
--;;
drop table invitees;
--;;
drop table user_sessions;
--;;
drop table user_authorities;
--;;
drop table users;
--;;
drop table authorities;
--;;
drop table user_statuses;
--;;
